### ISSUE TITLE
Agregar encoding utf-8 al request

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#62]
En la [linea 76 de request_xml.py](https://github.com/sihaysistema/factura_electronica_gt/blob/master/factura_electronica/request_xml.py#L76), ¿es necesario agregarle encoding utf8 para asegurar se envíen caracteres adecuados?

Antes: <?xml version="1.0" ?>

Después:  <?xml version="1.0" encoding="utf-8"?>

**Comment by monroy95** [comment]
@Tropicalrambler con y sin el encoding `utf8` no se detecto problema ni diferencias, pero será agregado al encabezado:
`<?xml version="1.0" encoding="UTF-8"?>`

**Comment by Tropicalrambler** [comment]
En efecto, sin relación alguna hubieron errores cuando se intento enviar una factura, cuyo nombre de cliente poseía caracteres como "ç" "cedille" y  "&" -  ["et"](http://dle.rae.es/?id=H3AJ9YW) en [https://es.wikipedia.org/wiki/&](Wikipedia).  Se continuará evaluando si es necesario ajustar el encoding en el XML o en otro lugar.

**Comment by Tropicalrambler** [comment]
### Esto arroja Frappe
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/factura_electronica/factura_electronica/api.py", line 172, in generar_factura_electronica
    descripciones = (documento_descripcion['S:Envelope']['S:Body']['ns2:registrarDteResponse']['return']['descripcion'])
KeyError: 'ns2:registrarDteResponse'

### Esto responde INFILE:
La respuesta de INFILE es: S:Server[com.ctc.wstx.exc.WstxLazyException] Unexpected character
 ' ' (code 32) (missing name?) at [row,col {unknown-source}]: [69,51][com.ctc.wstx.exc.WstxLazyException] Unexpected character ' 
 ' (code 32) (missing name?) at [row,col {unknown-source}]: [69,51]Unexpected character ' ' (code 32) (missing name?) at [row,col {unknown-source}]: [69,51]
